version: 2
updates:
      
    # Keep Docker dependencies up to date
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    # Raise pull requests for Docker version updates
    # against the "master" branch. The Docker configuration
    # no longer affects security update pull requests.
    target-branch: "master"
    # Use custom labels on pull requests for Docker version updates
    labels:
      - "Docker dependencies"
